package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// charMap maps accented/special characters to ASCII equivalents for slug generation.
var charMap = map[rune]string{
	'à': "a", 'á': "a", 'â': "a", 'ã': "a", 'ä': "a", 'å': "a",
	'æ': "ae", 'ç': "c", 'è': "e", 'é': "e", 'ê': "e", 'ë': "e",
	'ì': "i", 'í': "i", 'î': "i", 'ï': "i", 'ð': "d", 'ñ': "n",
	'ò': "o", 'ó': "o", 'ô': "o", 'õ': "o", 'ö': "o", 'ø': "o",
	'ù': "u", 'ú': "u", 'û': "u", 'ü': "u", 'ý': "y", 'ÿ': "y",
	'ß': "ss", 'þ': "th",
	// Eastern European
	'ą': "a", 'ć': "c", 'ę': "e", 'ł': "l", 'ń': "n", 'ś': "s",
	'ź': "z", 'ż': "z", 'č': "c", 'ď': "d", 'ě': "e", 'ň': "n",
	'ř': "r", 'š': "s", 'ť': "t", 'ž': "z", 'ů': "u",
	'ă': "a", 'ș': "s", 'ț': "t",
	// Turkish
	'ğ': "g", 'ı': "i", 'ş': "s",
	// Croatian/Serbian
	'đ': "d",
}

var (
	rePretalxCode   = regexp.MustCompile(`(?m)^pretalx_code:\s*"([^"]*)"`)
	rePretalxPrefix = regexp.MustCompile(`(?m)^pretalx_prefix:\s*"([^"]*)"`)
)

// slugify converts a string into a URL-friendly slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	prevHyphen := false

	for _, r := range s {
		if rep, ok := charMap[r]; ok {
			b.WriteString(rep)
			prevHyphen = false
			continue
		}
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevHyphen = false
		} else if r == ' ' || r == '-' || r == '_' || r == '/' {
			if !prevHyphen && b.Len() > 0 {
				b.WriteByte('-')
				prevHyphen = true
			}
		}
		// All other characters are silently dropped
	}

	return strings.TrimRight(b.String(), "-")
}

// getStr extracts a string value from a map, handling both simple strings
// and Pretalx multi-language objects (e.g. {"en": "Talk"}).
func getStr(m map[string]interface{}, key string) string {
	v, ok := m[key]
	if !ok {
		return ""
	}
	switch val := v.(type) {
	case string:
		return val
	case map[string]interface{}:
		// Multi-language: prefer "en", then first available
		if en, ok := val["en"]; ok {
			return fmt.Sprintf("%v", en)
		}
		for _, v := range val {
			return fmt.Sprintf("%v", v)
		}
		return ""
	default:
		return fmt.Sprintf("%v", v)
	}
}

// writeDataFile writes a JSON data file to the given path.
// Data files are always overwritten (they represent the current API state).
func writeDataFile(path string, data []interface{}, dryRun bool) error {
	if dryRun {
		fmt.Printf("  [dry-run] Would write %s (%d items)\n", path, len(data))
		return nil
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	content, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling JSON: %w", err)
	}
	content = append(content, '\n')

	if err := os.WriteFile(path, content, 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	fmt.Printf("  Wrote %s (%d items)\n", path, len(data))
	return nil
}

// resolveSlug picks a unique slug under content/<section>/, trying base, base-1, base-2, …
// If an existing page has the same pretalx_code + pretalx_prefix, that slug is reused (idempotent).
func resolveSlug(outputDir, section, baseSlug, code, prefix string, used map[string]bool) string {
	for i := 0; ; i++ {
		slug := baseSlug
		if i > 0 {
			slug = fmt.Sprintf("%s-%d", baseSlug, i)
		}
		if used[slug] {
			continue
		}
		path := filepath.Join(outputDir, "content", section, slug, "index.md")
		if !fileExists(path) {
			used[slug] = true
			return slug
		}
		if matchesPretalxIdentity(path, code, prefix) {
			used[slug] = true
			return slug
		}
	}
}

// pretalxIdentity is the (code, prefix) pair identifying which Pretalx item a page was generated from.
type pretalxIdentity struct {
	Code   string
	Prefix string
}

// readPretalxIdentity reads a page's generated identity from its front matter.
// The second return value is false for pages that were not generated by this tool.
func readPretalxIdentity(path string) (pretalxIdentity, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return pretalxIdentity{}, false
	}
	content := string(data)
	codeMatch := rePretalxCode.FindStringSubmatch(content)
	prefixMatch := rePretalxPrefix.FindStringSubmatch(content)
	if codeMatch == nil || prefixMatch == nil {
		return pretalxIdentity{}, false
	}
	return pretalxIdentity{Code: codeMatch[1], Prefix: prefixMatch[1]}, true
}

// matchesPretalxIdentity reports whether path's front matter has the given code and prefix.
func matchesPretalxIdentity(path, code, prefix string) bool {
	identity, ok := readPretalxIdentity(path)
	return ok && identity.Code == code && identity.Prefix == prefix
}

// generateRequest describes one event's content generation pass.
type generateRequest struct {
	OutputDir string
	Event     EventConfig
	Talks     []interface{}
	Speakers  []interface{}
	DryRun    bool
	Force     bool
	Prune     bool // remove previously generated pages that are no longer in the fetched set
}

// generateContent creates Hugo content pages for talks, speakers, and section indices.
func generateContent(req generateRequest) error {
	outputDir := req.OutputDir
	event := req.Event
	dryRun := req.DryRun
	force := req.Force

	prefix := event.Prefix
	talkLayout := event.TalkLayout
	if talkLayout == "" {
		talkLayout = "pretalx-talk"
	}
	speakerLayout := event.SpeakerLayout
	if speakerLayout == "" {
		speakerLayout = "pretalx-speaker"
	}

	// Flat section indexes (skip if present unless --force so hand-maintained indexes stay)
	sections := []struct {
		relPath string
		title   string
		layout  string
	}{
		{filepath.Join("content", "talks", "_index.md"), "Talks", "pretalx-talks"},
		{filepath.Join("content", "speakers", "_index.md"), "Speakers", "pretalx-speakers"},
		{filepath.Join("content", "schedule", "_index.md"), "Schedule", "pretalx-schedule"},
	}

	for _, s := range sections {
		path := filepath.Join(outputDir, s.relPath)
		if err := writeSectionIndex(path, s.title, s.layout, prefix, dryRun, force); err != nil {
			return err
		}
	}

	images := newImageDownloader(dryRun)

	usedTalkSlugs := make(map[string]bool)
	talkCodes := make(map[string]bool)
	for _, item := range req.Talks {
		m, ok := item.(map[string]interface{})
		if !ok {
			continue
		}
		title := getStr(m, "title")
		code := getStr(m, "code")
		if title == "" || code == "" {
			continue
		}
		baseSlug := slugify(title)
		if baseSlug == "" {
			baseSlug = strings.ToLower(code)
		}
		slug := resolveSlug(outputDir, "talks", baseSlug, code, prefix, usedTalkSlugs)
		path := filepath.Join(outputDir, "content", "talks", slug, "index.md")
		tags := append(append([]string{}, event.Tags...), "talk")
		if err := writeContentPage(path, title, talkLayout, code, prefix, tags, dryRun, force); err != nil {
			return err
		}
		images.Mirror(imageRequest{URL: getStr(m, "image"), Dir: filepath.Dir(path)})
		talkCodes[code] = true
	}
	if !dryRun {
		fmt.Printf("  Generated %d talk pages\n", len(talkCodes))
	}

	usedSpeakerSlugs := make(map[string]bool)
	speakerCodes := make(map[string]bool)
	for _, item := range req.Speakers {
		m, ok := item.(map[string]interface{})
		if !ok {
			continue
		}
		name := getStr(m, "name")
		code := getStr(m, "code")
		if name == "" || code == "" {
			continue
		}
		baseSlug := slugify(name)
		if baseSlug == "" {
			baseSlug = strings.ToLower(code)
		}
		slug := resolveSlug(outputDir, "speakers", baseSlug, code, prefix, usedSpeakerSlugs)
		path := filepath.Join(outputDir, "content", "speakers", slug, "index.md")
		tags := append(append([]string{}, event.Tags...), "speaker")
		if err := writeContentPage(path, name, speakerLayout, code, prefix, tags, dryRun, force); err != nil {
			return err
		}
		images.Mirror(imageRequest{URL: getStr(m, "avatar"), Dir: filepath.Dir(path)})
		speakerCodes[code] = true
	}
	if !dryRun {
		fmt.Printf("  Generated %d speaker pages\n", len(speakerCodes))
		fmt.Printf("  Images: %s\n", images.Summary())
	}

	if !req.Prune {
		return nil
	}

	for _, section := range []struct {
		name  string
		codes map[string]bool
	}{
		{"talks", talkCodes},
		{"speakers", speakerCodes},
	} {
		if err := pruneSection(pruneRequest{
			OutputDir: outputDir,
			Section:   section.name,
			Prefix:    prefix,
			Codes:     section.codes,
			DryRun:    dryRun,
		}); err != nil {
			return err
		}
	}

	return nil
}

// pruneRequest describes which generated pages of a section are still current.
type pruneRequest struct {
	OutputDir string
	Section   string          // content section directory, e.g. "talks"
	Prefix    string          // only pages of this pretalx_prefix are considered
	Codes     map[string]bool // pretalx_code values that are still in the fetched set
	DryRun    bool
}

// pruneSection deletes page bundles that this tool generated for req.Prefix but that
// are no longer part of the fetched set (withdrawn talks, submissions excluded by the
// event's states, speakers who lost their last talk). Pages that are hand-written,
// belong to another event prefix, or carry a manual body are always left alone.
func pruneSection(req pruneRequest) error {
	dir := filepath.Join(req.OutputDir, "content", req.Section)
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", dir, err)
	}

	removed, kept := 0, 0
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		bundle := filepath.Join(dir, entry.Name())
		path := filepath.Join(bundle, "index.md")
		identity, ok := readPretalxIdentity(path)
		if !ok || identity.Prefix != req.Prefix || req.Codes[identity.Code] {
			continue
		}
		if extractBody(path) != "" {
			fmt.Printf("  Kept %s (has manual content)\n", bundle)
			kept++
			continue
		}
		if req.DryRun {
			fmt.Printf("  [dry-run] Would remove %s\n", bundle)
			removed++
			continue
		}
		if err := os.RemoveAll(bundle); err != nil {
			return fmt.Errorf("removing %s: %w", bundle, err)
		}
		removed++
	}

	verb := "Pruned"
	if req.DryRun {
		verb = "Would prune"
	}
	summary := fmt.Sprintf("  %s %d stale pages in content/%s", verb, removed, req.Section)
	if kept > 0 {
		summary += fmt.Sprintf(" (%d kept with manual content)", kept)
	}
	fmt.Println(summary)
	return nil
}

// writeSectionIndex creates or updates a section _index.md file.
func writeSectionIndex(path, title, layout, prefix string, dryRun, force bool) error {
	if !force && fileExists(path) {
		return nil
	}

	if dryRun {
		fmt.Printf("  [dry-run] Would write %s\n", path)
		return nil
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	var buf strings.Builder
	buf.WriteString("---\n")
	buf.WriteString(fmt.Sprintf("title: %q\n", title))
	if layout != "" {
		buf.WriteString(fmt.Sprintf("layout: %q\n", layout))
	}
	buf.WriteString(fmt.Sprintf("pretalx_prefix: %q\n", prefix))
	buf.WriteString("---\n")

	if err := os.WriteFile(path, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	fmt.Printf("  Created %s\n", path)
	return nil
}

// writeContentPage creates or updates a content page (talk or speaker).
// When force=true and the file already exists, front matter is regenerated
// but any manually-added body content below the front matter is preserved.
func writeContentPage(path, title, layout, code, prefix string, tags []string, dryRun, force bool) error {
	exists := fileExists(path)

	if exists && !force {
		return nil
	}

	if dryRun {
		action := "Would create"
		if exists {
			action = "Would update"
		}
		fmt.Printf("  [dry-run] %s %s\n", action, path)
		return nil
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	// Preserve manually-added body content on update
	existingBody := ""
	if exists {
		existingBody = extractBody(path)
	}

	var buf strings.Builder
	buf.WriteString("---\n")
	buf.WriteString(fmt.Sprintf("title: %q\n", title))
	buf.WriteString(fmt.Sprintf("layout: %q\n", layout))
	buf.WriteString(fmt.Sprintf("pretalx_code: %q\n", code))
	buf.WriteString(fmt.Sprintf("pretalx_prefix: %q\n", prefix))
	if len(tags) > 0 {
		buf.WriteString("tags:\n")
		for _, t := range tags {
			buf.WriteString(fmt.Sprintf("  - %q\n", t))
		}
	}
	buf.WriteString("---\n")

	if existingBody != "" {
		buf.WriteString(existingBody)
	}

	if err := os.WriteFile(path, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// extractBody reads a Hugo content file and returns everything after the
// closing front matter delimiter ("---"). Returns empty string if no body.
func extractBody(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	content := string(data)

	// Front matter is delimited by "---" at start and end.
	// Split on "---\n" — the third part (if any) is the body.
	const delim = "---\n"
	if !strings.HasPrefix(content, delim) {
		return ""
	}
	rest := content[len(delim):]
	idx := strings.Index(rest, delim)
	if idx < 0 {
		return ""
	}
	body := rest[idx+len(delim):]
	if strings.TrimSpace(body) == "" {
		return ""
	}
	return body
}

// fileExists checks whether a file exists at the given path.
func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
